### ISSUE TITLE
What are the legitimate values here?

### ISSUE THREAD

**Issue by bkwsoft** [WAHU-Robotics/rov#2]
https://github.com/jbuelow1/rov/blob/37de56d20f00678b01347ea2c69e9653f5fa6fc2/common/src/main/java/me/jbuelow/rov/common/MotorPower.java#L25

Documentation (comments) indicate -100 to 100 aka -100% to 100% thrust.  It appears that that the actual values being transmitted are outside of that range.  So what is the true range?  Do we actually need more than 100 steps in each direction?

**Comment by yammyshep** [comment]
it is 1000  to -1000. Once i move control logic to wet, ill adjust to match this comment.

**Comment by yammyshep** [comment]
Fixed since commit 10c5839
